language: scala
scala:
    - 2.12.2
script:
    - sbt clean coverage test
    - sbt coverageReport
after_success:
    - sbt coveralls

sudo: required

services:
  - docker

before_install:
  - docker pull rabbitmq
  - docker run -d --hostname my-rabbit-server --name my-rabbitmq rabbitmq
