language: scala
scala:
    - 2.12.2
script:
    - sbt clean coverage test
    - sbt coverageReport
    - sbt it:clean it:test
after_success:
    - sbt coveralls

sudo: required

services:
  - docker

before_install:
  - docker run -d --hostname my-rabbit --name my-rabbit -p 15671-15672:15671-15672/tcp -p 5671-5672:5671-5672/tcp -p 61613:61613 rabbitmq:3-management
  - docker ps -a
